### ISSUE TITLE
Compiling on Ubuntu 11.10 64-bit

### ISSUE THREAD

**Issue by ldesousa** [minad/osm2shp#3]
Dear minad,

This program doesn't compile on Ubuntu 11.10 64-bit. Here's the output: 

$ make
g++ -ggdb -Wall -Wredundant-decls -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c osm2shp.cc -o osm2shp.o
In file included from osm/handler.hpp:4:0,
                 from osm2shp.cc:1:
osm/point_database.hpp:6:29: fatal error: boost/utility.hpp: No such file or directory
compilation terminated.
make: **\* [osm2shp.o] Error 1

Any workaround possible? Thanks.
